#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run=git
/**
 * aur.ts — the AUR package of the desktop app, `agents-multi-bin` (docs/adr/0004): the release's deb,
 * repackaged for pacman, with the app's updater off (pacman updates it). AUR follows the stable channel.
 *
 *   aur.ts render <version> <sha256 of the deb> [dir]   writes PKGBUILD and .SRCINFO (default
 *                                                       pkg/agents-multi-bin)
 *   aur.ts push <dir> [--dry-run]                       clones the AUR repository over SSH, puts the two
 *                                                       files in, commits and pushes; needs the AUR key
 *                                                       in the SSH agent or GIT_SSH_COMMAND. --dry-run
 *                                                       stops before the push
 *
 * Everything the package says comes from apps/desktop/release.json (the GitHub repository, the AUR
 * name, the licence) and tauri.conf.json (the identifier, which names the deb's resource folder).
 */

import { isPre, parseVersion } from "./release.ts";
import { gitIn } from "./lib/git.ts";
import { assetName, downloadUrl, RELEASE_CONFIG, type ReleaseConfig, TAURI_CONFIG } from "./app-release.ts";

export interface Package {
  name: string;
  version: string;
  sha256: string;
  github: string;
  license: string;
  /** the bundle identifier: the deb puts the app's resources in /usr/lib/<identifier> */
  identifier: string;
}

/** What the app needs from Arch: the deb's dependencies, in pacman's names (the deb also lists
 *  libayatana-appindicator, which the app does not load on Linux: its tray is its own, ADR 0003). */
export const DEPENDS = ["webkit2gtk-4.1", "gtk3", "hicolor-icon-theme"];

const DESCRIPTION = "Several Claude Code and Claude Desktop accounts on one machine, one console for all";

/** Pure: why these values cannot make a package, empty when they can. */
export function packageProblems(p: Package): string[] {
  const out: string[] = [];
  let beta = false;
  try {
    beta = isPre(parseVersion(p.version));
  } catch {
    out.push(`not a version: ${p.version}`);
  }
  if (beta) out.push("the AUR package follows the stable channel, not pre-releases");
  if (!/^[0-9a-f]{64}$/.test(p.sha256)) out.push("the deb's sha256 is not 64 hex digits");
  if (!/^[\w.-]+\/[\w.-]+$/.test(p.github)) out.push(`${RELEASE_CONFIG}: "github" is not owner/name`);
  if (!p.license.trim()) out.push(`${RELEASE_CONFIG}: "license" is empty (an SPDX identifier)`);
  if (!/^[a-z0-9][a-z0-9.+_-]*$/.test(p.name)) out.push(`${RELEASE_CONFIG}: "aur" is not a package name`);
  return out;
}

/** Pure: the PKGBUILD. */
export function pkgbuild(p: Package): string {
  const source = `https://github.com/${p.github}/releases/download/v\${pkgver}/${assetName("deb", "${pkgver}")}`;
  return `# Generated by scripts/aur.ts from the release: edit the script, not this file.
pkgname=${p.name}
pkgver=${p.version}
pkgrel=1
pkgdesc="${DESCRIPTION}"
arch=('x86_64')
url="https://github.com/${p.github}"
license=('${p.license}')
depends=(${DEPENDS.map((d) => `'${d}'`).join(" ")})
provides=('agents-multi')
conflicts=('agents-multi')
# the bundled Deno is a release binary of its own: stripping it again gains nothing
options=('!strip' '!debug')
source_x86_64=("${source}")
sha256sums_x86_64=('${p.sha256}')

package() {
  bsdtar -xf data.tar.* -C "$pkgdir"
  # pacman updates the app: its own updater stays off (apps/desktop/src-tauri/src/updater.rs)
  printf 'pacman\\n' > "$pkgdir/usr/lib/${p.identifier}/package-manager"
  # the licence carries additional terms (attribution): its text goes where pacman looks for it
  for f in LICENSE THIRD_PARTY_NOTICES.md; do
    install -Dm644 "$pkgdir/usr/lib/${p.identifier}/repo/$f" "$pkgdir/usr/share/licenses/$pkgname/$f"
  done
}
`;
}

/** Pure: the .SRCINFO the AUR reads, the same fields as the PKGBUILD (makepkg --printsrcinfo's layout). */
export function srcinfo(p: Package): string {
  const deb = assetName("deb", p.version);
  return [
    `pkgbase = ${p.name}`,
    `\tpkgdesc = ${DESCRIPTION}`,
    `\tpkgver = ${p.version}`,
    `\tpkgrel = 1`,
    `\turl = https://github.com/${p.github}`,
    `\tarch = x86_64`,
    `\tlicense = ${p.license}`,
    ...DEPENDS.map((d) => `\tdepends = ${d}`),
    `\tprovides = agents-multi`,
    `\tconflicts = agents-multi`,
    `\toptions = !strip`,
    `\toptions = !debug`,
    `\tsource_x86_64 = ${downloadUrl(p.github, p.version, deb)}`,
    `\tsha256sums_x86_64 = ${p.sha256}`,
    ``,
    `pkgname = ${p.name}`,
    ``,
  ].join("\n");
}

async function render(version: string, sha256: string, dir: string) {
  const config = JSON.parse(await Deno.readTextFile(RELEASE_CONFIG)) as ReleaseConfig;
  const tauri = JSON.parse(await Deno.readTextFile(TAURI_CONFIG)) as { identifier: string };
  const p: Package = {
    name: config.aur,
    version,
    sha256: sha256.toLowerCase(),
    github: config.github,
    license: config.license ?? "",
    identifier: tauri.identifier,
  };
  const problems = packageProblems(p);
  if (problems.length) throw new Error(problems.join("; "));
  await Deno.mkdir(dir, { recursive: true });
  await Deno.writeTextFile(`${dir}/PKGBUILD`, pkgbuild(p));
  await Deno.writeTextFile(`${dir}/.SRCINFO`, srcinfo(p));
  console.log(`${p.name} ${version} in ${dir}`);
}

async function push(dir: string, dry: boolean) {
  const config = JSON.parse(await Deno.readTextFile(RELEASE_CONFIG)) as ReleaseConfig;
  const work = await Deno.makeTempDir({ prefix: "aur-" });
  try {
    await gitIn(work, "clone", "--quiet", `ssh://aur@aur.archlinux.org/${config.aur}.git`, "repo");
    for (const f of ["PKGBUILD", ".SRCINFO"]) await Deno.copyFile(`${dir}/${f}`, `${work}/repo/${f}`);
    const version = /^pkgver=(.+)$/m.exec(await Deno.readTextFile(`${dir}/PKGBUILD`))?.[1] ?? "?";
    await gitIn(`${work}/repo`, "add", "PKGBUILD", ".SRCINFO");
    const status = await new Deno.Command("git", { args: ["diff", "--cached", "--quiet"], cwd: `${work}/repo` })
      .output();
    if (status.success) {
      console.log(`${config.aur} is already at ${version}`);
      return;
    }
    await gitIn(`${work}/repo`, "commit", "--quiet", "-m", `${version}`);
    if (dry) {
      console.log(`${config.aur} ${version}: committed in ${work}/repo, not pushed (--dry-run)`);
      return;
    }
    await gitIn(`${work}/repo`, "push", "--quiet", "origin", "HEAD:master");
    console.log(`${config.aur} ${version} pushed to the AUR`);
  } finally {
    if (!dry) await Deno.remove(work, { recursive: true });
  }
}

async function main(args: string[]) {
  const dry = args.includes("--dry-run");
  const [cmd, a, b, c] = args.filter((x) => !x.startsWith("--"));
  if (cmd === "render" && a && b) await render(a, b, c ?? "pkg/agents-multi-bin");
  else if (cmd === "push" && a) await push(a, dry);
  else throw new Error("usage: aur.ts render <version> <sha256> [dir] | push <dir> [--dry-run]");
}

if (import.meta.main) {
  try {
    await main(Deno.args);
  } catch (e) {
    console.error(`aur: ${(e as Error).message}`);
    Deno.exit(1);
  }
}
